

"use client"

import { useState, useEffect, useCallback } from 'react';
import type { CoverageEntry } from '@/lib/types';
import { useToast } from "@/hooks/use-toast";
import { db } from '@/lib/firebase';
import { collection, addDoc, getDocs, query, where, doc, deleteDoc, updateDoc, writeBatch } from 'firebase/firestore';
import { isSameDay, parseISO } from 'date-fns';

const OFFLINE_ENTRIES_KEY = 'sfe-offline-coverage-entries-v2';

// Simple and compatible unique ID generator
const generateUniqueId = () => {
    return `offline_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`;
};

export const useOfflineSync = (userId?: string) => {
  const { toast } = useToast();
  const [offlineEntries, setOfflineEntries] = useState<CoverageEntry[]>([]);
  const [masterEntries, setMasterEntries] = useState<CoverageEntry[]>([]);
  const [isSyncing, setIsSyncing] = useState(false);
  const [isOnline, setIsOnline] = useState(true); // Default to true, will be corrected by useEffect on client
  const [loading, setLoading] = useState(true);


  const getOfflineKey = useCallback(() => `${OFFLINE_ENTRIES_KEY}_${userId}`, [userId]);

  useEffect(() => {
    // This code now runs only on the client
    setIsOnline(navigator.onLine);
    
    const handleOnline = () => setIsOnline(true);
    const handleOffline = () => setIsOnline(false);
    
    window.addEventListener('online', handleOnline);
    window.addEventListener('offline', handleOffline);
    
    return () => {
      window.removeEventListener('online', handleOnline);
      window.removeEventListener('offline', handleOffline);
    };
  }, []);

  const fetchMasterEntries = useCallback(async () => {
    if (!userId || !isOnline) {
      setLoading(false);
      return;
    }
    try {
      const q = query(collection(db, "coverageEntries"), where("userId", "==", userId));
      const querySnapshot = await getDocs(q);
      const entries: CoverageEntry[] = [];
      querySnapshot.forEach(doc => {
        entries.push({ id: doc.id, ...doc.data() } as CoverageEntry);
      });
      setMasterEntries(entries.sort((a,b) => new Date(b.submittedAt).getTime() - new Date(a.submittedAt).getTime()));
    } catch (error) {
      console.error("Error fetching master entries:", error);
      toast({ variant: "destructive", title: "Sync Error", description: "Could not fetch submitted entries from the server." });
    } finally {
        setLoading(false);
    }
  }, [userId, isOnline, toast]);
  
  useEffect(() => {
    if (userId) {
        // Load offline entries from local storage immediately
        try {
            const localData = localStorage.getItem(getOfflineKey());
            if (localData) {
                setOfflineEntries(JSON.parse(localData));
            }
        } catch (error) {
            console.error("Failed to parse offline entries from local storage:", error);
        }
        
        // Then fetch master entries from Firestore
        setLoading(true);
        fetchMasterEntries();
    } else {
      setOfflineEntries([]);
      setMasterEntries([]);
      setLoading(false);
    }
  }, [userId, getOfflineKey, fetchMasterEntries]);


  const updateOfflineInStorage = (updatedEntries: CoverageEntry[]) => {
      setOfflineEntries(updatedEntries);
      localStorage.setItem(getOfflineKey(), JSON.stringify(updatedEntries));
  }

  const saveEntry = async (entry: Omit<CoverageEntry, 'id' | 'submittedAt' | 'userId'>): Promise<boolean> => {
    if (!userId) {
        toast({ variant: 'destructive', title: 'Not logged in', description: 'You must be logged in to save entries.'});
        return false;
    }
    
    const newEntryPayload = {
      ...entry,
      userId: userId,
      submittedAt: new Date().toISOString(),
    };

    if (isOnline) {
        try {
            const { id, ...dataToSync } = { ...newEntryPayload, id: 'temp' }; // id is generated by firestore
            const docRef = await addDoc(collection(db, "coverageEntries"), dataToSync);
            setMasterEntries(prev => [{ ...dataToSync, id: docRef.id }, ...prev]);
            toast({ title: "Entry Saved", description: "Your coverage report has been saved to the server." });
            return true;
        } catch(error) {
            console.error("Error saving entry online, saving locally instead:", error);
            saveEntryOffline(newEntryPayload);
            return false;
        }
    } else {
        saveEntryOffline(newEntryPayload);
        return false;
    }
  };

  const saveEntryOffline = (newEntry: Omit<CoverageEntry, 'id'> & { id?: string }) => {
    const entryWithId = {
        ...newEntry,
        id: newEntry.id || generateUniqueId(),
    }
    const currentOfflineEntries = offlineEntries;
    const updatedEntries = [...currentOfflineEntries, entryWithId];
    setOfflineEntries(updatedEntries);
    localStorage.setItem(getOfflineKey(), JSON.stringify(updatedEntries));
    toast({ title: "Entry Saved Locally", description: "You are offline. Report will sync when you're back online." });
  }

  const deleteMasterEntry = async (id: string) => {
    try {
        const entryToDelete = masterEntries.find(e => e.id === id);
        await deleteDoc(doc(db, "coverageEntries", id));
        setMasterEntries(prev => prev.filter(e => e.id !== id));
        if(entryToDelete) {
            toast({ variant: 'destructive', title: "Entry Deleted", description: `Coverage for ${entryToDelete.firstName} ${entryToDelete.lastName} has been removed.` });
        }
    } catch (error) {
        toast({ variant: 'destructive', title: "Delete Failed", description: "Could not delete entry from server." });
    }
  };

  const updateMasterEntry = async (entryToUpdate: Omit<CoverageEntry, 'submittedAt'>) => {
    try {
        const entryRef = doc(db, "coverageEntries", entryToUpdate.id);
        await updateDoc(entryRef, { ...entryToUpdate });
        setMasterEntries(prev => prev.map(e => e.id === entryToUpdate.id ? { ...e, ...entryToUpdate } : e));
        toast({ title: "Entry Updated", description: `Changes for ${entryToUpdate.firstName} ${entryToUpdate.lastName} have been saved.` });
    } catch (error) {
        toast({ variant: 'destructive', title: "Update Failed", description: "Could not update entry on server." });
    }
  };

  const updateOfflineEntry = (entryToUpdate: CoverageEntry) => {
    const updatedEntries = offlineEntries.map(e => e.id === entryToUpdate.id ? entryToUpdate : e);
    updateOfflineInStorage(updatedEntries);
    toast({ title: "Offline Entry Updated", description: `Changes for ${entryToUpdate.firstName} ${entryToUpdate.lastName} have been saved locally.` });
  };

  const syncAllOfflineEntries = useCallback(async () => {
    if (!isOnline || !userId || offlineEntries.length === 0 || isSyncing) {
      if (offlineEntries.length === 0 && !isSyncing) toast({ title: "No Entries to Sync" });
      if (!isOnline && !isSyncing) toast({ title: "Cannot Sync", description: "You are currently offline." });
      return;
    }

    setIsSyncing(true);
    toast({ title: 'Syncing...', description: `Uploading ${offlineEntries.length} offline reports.`});

    let successfulSyncs: string[] = [];
    let failedSyncs: CoverageEntry[] = [];

    for (const entry of offlineEntries) {
        try {
            const { id, ...dataToSync } = entry;
            await addDoc(collection(db, "coverageEntries"), dataToSync);
            successfulSyncs.push(id);
        } catch (error) {
            console.error(`Failed to sync entry ${entry.id}:`, error);
            failedSyncs.push(entry);
        }
    }

    // Update local storage with any entries that failed to sync
    updateOfflineInStorage(failedSyncs);

    if (successfulSyncs.length > 0) {
        toast({
            title: 'Sync Partially Complete',
            description: `${successfulSyncs.length} of ${offlineEntries.length} entries synced successfully.`,
        });
        await fetchMasterEntries(); // Refresh master entries after successful sync
    }

    if (failedSyncs.length > 0) {
        toast({
            variant: 'destructive',
            title: 'Sync Incomplete',
            description: `${failedSyncs.length} entries failed to sync. They remain offline for the next attempt.`,
        });
    }

    if (successfulSyncs.length > 0 && failedSyncs.length === 0) {
        toast({ title: 'Sync Complete', description: `All ${successfulSyncs.length} entries synced successfully.` });
    }

    setIsSyncing(false);
  }, [isOnline, userId, offlineEntries, toast, fetchMasterEntries, isSyncing, getOfflineKey]);

  return { offlineEntries, masterEntries, saveEntry, deleteMasterEntry, isSyncing, syncAllOfflineEntries, isOnline, updateMasterEntry, updateOfflineEntry, loading };
};
